#! /bin/sh


bspc monitor -d code music web

bspc config border_width         0
bspc config window_gap           25

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
bspc config ignore_ewmh_focus false


bspc config pointer_action1 move
bspc config pointer_action2 none
bspc config pointer_action3 resize_corner
bspc config click_to_focus true
#bspc config focus_follows_pointer true

sxhkd &
# $HOME/.config/polybar/launch.sh
compton -b
#conky &
razer-daemon
python ~/Development/guage/desktop.py &
